# permissions for end users to edit springbootapplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: springbootapplication-editor-role
  labels:
    bindings.projectriff.io/controller: "true"
rules:
- apiGroups:
  - apps.mononoke.local
  resources:
  - springbootapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.mononoke.local
  resources:
  - springbootapplications/status
  verbs:
  - get
